server:
  port: 9100 # 后期该微服务多实例，端口从9100递增（10个以内）
Spring:
  application:
    name: lagou-service-page
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.179.128:3306/ms?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: ChenLijun@666



eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:9200/eureka/
  instance:
#使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
#自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT

#针对的被调用方微服务名称,不加就是全局生效
chen-service-product:
  ribbon:
    #请求连接超时时间
    ConnectTimeout: 2000
    #请求处理超时时间
    ReadTimeout: 5000
    #对所有操作都进行重试
    OkToRetryOnAllOperations: true
    ####根据如上配置，当访问到故障请求的时候，它会再尝试访问一次当前实例（次数由 MaxAutoRetries配置），
    ####如果不行，就换一个实例进行访问，如果还不行，再换一次实例访问（更换次数由MaxAutoRetriesNextServer配置），
    ####如果依然不行，返回失败信息。
    MaxAutoRetries: 0 #对当前选中实例重试次数，不包括第一次调用
    MaxAutoRetriesNextServer: 0 #切换实例的重试次数
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略    调整

hystrix:
  command:
    default:
      circuitBreaker:
  # 强制打开熔断器，如果该属性设置为true，强制断路器进入打开状态，将会拒绝所有的请求。  默认false关闭的
        forceOpen: false
# 触发熔断错误比例阈值，默认值50%
        errorThresholdPercentage: 50
# 熔断后休眠时长，默认值5秒
        sleepWindowInMilliseconds: 3000
# 熔断触发最小请求次数，默认值是20
        requestVolumeThreshold: 2
    execution:
      isolation:
        thread:
# 熔断超时设置，默认为1秒
          timeoutInMilliseconds: 2000
# springboot中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
# 暴露健康接口的细节
  endpoint:
    health:
      show-details: always

#hystrix:
#  threadpool:
#    default:
#      coreSize: 10 #并发执行的最大线程数，默认10
#      maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
#      queueSizeRejectionThreshold: 1500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5

# queueSizeRejectionThreshold,maxQueueSize 需要同时设置
feign:
  hystrix:
    enabled: true
  compression: #请求压缩
    request:
      enabled: true
      mime-types: text/xml, application/xml, application/json #默认值
      min-request-size: 2048 #默认值
    response:
      enabled: true

