server:
  port: 9100 # 后期该微服务多实例，端口从9100递增（10个以内）
Spring:
  application:
    name: lagou-service-page
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.179.128:3306/ms?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: ChenLijun@666



eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:9200/eureka/
  instance:
#使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
#自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

#针对的被调用方微服务名称,不加就是全局生效
chen-service-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略
# springboot中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
# 暴露健康接口的细节
  endpoint:
    health:
      show-details: always

#hystrix:
#  threadpool:
#    default:
#      coreSize: 10 #并发执行的最大线程数，默认10
#      maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
#      queueSizeRejectionThreshold: 1500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5

# queueSizeRejectionThreshold,maxQueueSize 需要同时设置